# Generated by Django 4.2.30 on 2026-08-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('rrhh', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='nomina',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='rrhh.nomina'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='compras.compra'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compra__isnull', False), ('nomina__isnull', True)), models.Q(('compra__isnull', True), ('nomina__isnull', False)), _connector='OR'), name='cuenta_por_pagar_origen_unico'),
        ),
    ]
