# Generated by Django 4.2.30 on 2026-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cuentaporpagar_nomina_alter_cuentaporpagar_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
