# Generated by Django 4.2.30 on 2026-09-02 02:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0009_alter_departamento_nombre_alter_empleado_documento_and_more'),
        ('ventas', '0009_alter_cotizacion_numero_alter_cuentacobro_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_grupoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la obra')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación / dirección de la obra')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / alcance')),
                ('estado', models.CharField(choices=[('planificacion', 'En planificación'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=15)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Presupuesto total aprobado para la obra.', max_digits=14, verbose_name='Presupuesto')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional: a quién se le está construyendo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='ventas.cliente')),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('responsable', models.ForeignKey(blank=True, help_text='Quién dirige la obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_objetivo', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['orden', 'fecha_objetivo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GastoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('materiales', 'Materiales'), ('mano_obra', 'Mano de obra'), ('equipos', 'Equipos y herramientas'), ('otros', 'Otros')], default='otros', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='proyectos.proyecto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto de obra',
                'verbose_name_plural': 'Gastos de obra',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_obra', models.CharField(blank=True, help_text='Ej. maestro de obra, oficial, ayudante (si difiere del cargo habitual).', max_length=100, verbose_name='Rol en la obra')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_proyecto', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Asignación de empleado',
                'verbose_name_plural': 'Asignaciones de empleados',
                'ordering': ['-activo', 'empleado__nombre_completo'],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='proyecto_numero_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='asignacionempleado',
            constraint=models.UniqueConstraint(fields=('proyecto', 'empleado'), name='asignacion_unica_por_proyecto'),
        ),
    ]
