# Generated by Django 4.2.30 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra a proveedor'), ('venta', 'Venta a cliente'), ('ajuste', 'Ajuste manual'), ('devolucion', 'Devolución'), ('produccion', 'Producción')], default='ajuste', max_length=15),
        ),
    ]
