# Generated by Django 4.2.30 on 2026-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='ERP Gestión', max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT/Documento')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano (COP)'), ('USD', 'Dólar estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('MXN', 'Peso mexicano (MXN)')], default='COP', max_length=3)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
    ]
