# Generated by Django 4.2.30 on 2026-08-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('ver_dashboard', 'Puede ver el dashboard general')], 'verbose_name': 'Datos de la empresa', 'verbose_name_plural': 'Datos de la empresa'},
        ),
    ]
