# Generated by Django 4.2.30 on 2026-09-02 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_seed_empresa_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('ver_dashboard', 'Puede ver el dashboard general')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, help_text='Una empresa inactiva no permite iniciar sesión a sus usuarios.', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_superadmin_plataforma', models.BooleanField(default=False, help_text='Puede operar y cambiar entre todas las empresas registradas (uso interno del operador de la plataforma, no de un cliente).', verbose_name='Superadministrador de la plataforma')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
