# Generated by Django 4.2.30 on 2026-09-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_seed_perfiles_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.empresa')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vinculo', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol de empresa',
                'verbose_name_plural': 'Roles de empresa',
            },
        ),
    ]
