# Generated by Django 4.2.30 on 2026-09-02 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_grupoempresa'),
        ('proyectos', '0001_initial'),
        ('ventas', '0009_alter_cotizacion_numero_alter_cuentacobro_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('contrato', 'Contrato'), ('plano', 'Plano'), ('permiso', 'Permiso / licencia'), ('factura', 'Factura / soporte'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('archivo', models.FileField(help_text='pdf, doc, docx, xls, xlsx, ppt, pptx, jpg, jpeg, png, webp, dwg, zip. Máximo 20 MB.', upload_to=documentos.models.documento_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'webp', 'dwg', 'zip']), documentos.models.validar_tamano_archivo])),
                ('tamano_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional: si este documento pertenece a un cliente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ventas.cliente')),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Opcional: si este documento pertenece a una obra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos.proyecto')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
