# Generated by Django 4.2.30 on 2026-08-04 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('19'), help_text='Tarifa general de IVA en Colombia: 19%.', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
