# Generated by Django 4.2.30 on 2026-08-05 13:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_alter_movimientoinventario_motivo'),
        ('ventas', '0002_alter_venta_impuesto_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=12)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19'), help_text='Tarifa general de IVA en Colombia: 19%.', max_digits=5, verbose_name='IVA (%)')),
                ('fecha_validez', models.DateField(default=ventas.models._fecha_validez_por_defecto, verbose_name='Válida hasta')),
                ('notas', models.TextField(blank=True, help_text='Ej. forma de pago, tiempo de entrega, garantía.', verbose_name='Condiciones comerciales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ventas.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cotizacion', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Línea de cotización',
                'verbose_name_plural': 'Líneas de cotización',
            },
        ),
    ]
