# Generated by Django 4.2.30 on 2026-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cotizacion_lineacotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sede',
            field=models.CharField(blank=True, help_text='Sede o sucursal que atiende la cotización.', max_length=150, verbose_name='Sede'),
        ),
    ]
