# Generated by Django 4.2.30 on 2026-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cotizacion_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='firmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='firmado_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Firmado por'),
        ),
    ]
