# Generated by Django 4.2.30 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cotizacion_firmado_en_cotizacion_firmado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='facturada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Consecutivo de tu propia numeración de facturación.', max_length=30, null=True, unique=True, verbose_name='N° de factura'),
        ),
    ]
