# Generated by Django 4.2.30 on 2026-09-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0006_venta_facturada_en_venta_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=12)),
                ('emisor_tipo', models.CharField(choices=[('empresa', 'La empresa'), ('persona_natural', 'Persona natural')], default='empresa', max_length=16)),
                ('emisor_nombre', models.CharField(blank=True, help_text='Solo si se emite a nombre de una persona natural.', max_length=150, verbose_name='Nombre de quien cobra')),
                ('emisor_documento', models.CharField(blank=True, help_text='Solo si se emite a nombre de una persona natural.', max_length=30, verbose_name='Cédula de quien cobra')),
                ('concepto', models.TextField(help_text='Descripción del servicio o motivo del cobro.', verbose_name='Concepto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de expedición')),
                ('forma_pago', models.CharField(blank=True, help_text='Ej. transferencia, efectivo, consignación.', max_length=100)),
                ('datos_pago', models.CharField(blank=True, help_text='Ej. banco, tipo y número de cuenta, si aplica.', max_length=200, verbose_name='Datos de pago')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('emitida_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobro', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, help_text='Opcional: si esta cuenta de cobro corresponde a una venta ya registrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobro', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta de cobro',
                'verbose_name_plural': 'Cuentas de cobro',
                'ordering': ['-creado_en'],
            },
        ),
    ]
