# Generated by Django 4.2.30 on 2026-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_cliente_empresa_cotizacion_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Consecutivo de tu propia numeración de facturación.', max_length=30, null=True, verbose_name='N° de factura'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='cotizacion_numero_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cuentacobro',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='cuentacobro_numero_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='venta_numero_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_factura'), name='venta_numero_factura_unico_por_empresa'),
        ),
    ]
