# Generated by Django 4.2.30 on 2026-09-02 04:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('ventas', '0009_alter_cotizacion_numero_alter_cuentacobro_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Opcional: si esta cuenta de cobro se generó desde una cotización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobro', to='ventas.cotizacion'),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Opcional: si esta cuenta de cobro corresponde a una obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobro', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Opcional: si esta venta/factura corresponde a una obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('19'), help_text='Tarifa general de IVA en Colombia: 19%. Fija para facturas; solo el administrador puede cambiarla desde /admin/.', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
