# Generated by Django 4.2.30 on 2026-08-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='procesada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_procesadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
