# Generated by Django 4.2.30 on 2026-08-05 17:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0002_nomina_procesada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenomina',
            name='descuento_prestamo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Abono a préstamo'),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Horas extra'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_otorgado', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='rrhh.empleado')),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_otorgados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_otorgado'],
            },
        ),
        migrations.CreateModel(
            name='AbonoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_prestamo', to='rrhh.nomina')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='rrhh.prestamo')),
            ],
            options={
                'verbose_name': 'Abono a préstamo',
                'verbose_name_plural': 'Abonos a préstamos',
                'ordering': ['-fecha'],
            },
        ),
    ]
