# Generated by Django 4.2.30 on 2026-08-05 18:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_detallenomina_descuento_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenomina',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días trabajados'),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor por día'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_pago',
            field=models.CharField(choices=[('salario', 'Salario base (mensual)'), ('dia', 'Por día trabajado')], default='salario', max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor por día'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
