# Generated by Django 4.2.30 on 2026-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_detallenomina_dias_trabajados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='periodo',
            field=models.CharField(help_text='Mensual: AAAA-MM (ej. 2026-08). Semanal: AAAA-Www (ej. 2026-W32).', max_length=8, unique=True),
        ),
    ]
