# Generated by Django 4.2.30 on 2026-08-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_alter_nomina_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre_completo'], 'permissions': [('marcar_propia_asistencia', 'Puede registrar su propia entrada/salida')]},
        ),
    ]
