# Generated by Django 4.2.30 on 2026-08-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre_completo'], 'permissions': [('marcar_propia_asistencia', 'Puede registrar su propia entrada/salida'), ('ver_propio_perfil', 'Puede ver su propio perfil, asistencia, préstamos y recibos de nómina')]},
        ),
    ]
