# Generated by Django 4.2.30 on 2026-09-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_empresa_tenant'),
        ('rrhh', '0007_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonoprestamo',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
    ]
