# Generated by Django 4.2.30 on 2026-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_abonoprestamo_empresa_asistencia_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=30, verbose_name='Cédula/Documento'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='periodo',
            field=models.CharField(help_text='Mensual: AAAA-MM (ej. 2026-08). Semanal: AAAA-Www (ej. 2026-W32).', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='departamento_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'documento'), name='empleado_documento_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(fields=('empresa', 'periodo'), name='nomina_periodo_unico_por_empresa'),
        ),
    ]
