# Generated by Django 4.2.30 on 2026-09-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_alter_departamento_nombre_alter_empleado_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('termino_fijo', 'Contrato a término fijo'), ('prestacion_servicios', 'Contrato de prestación de servicios')], default='termino_fijo', help_text='Un contrato de prestación de servicios siempre se paga por día trabajado.', max_length=25, verbose_name='Tipo de contrato'),
        ),
    ]
