# Generated by Django 4.2.30 on 2026-09-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_grupoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fijado', models.BooleanField(default=False, help_text='Los comunicados fijados siempre aparecen primero.', verbose_name='Fijado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fijado', '-creado_en'],
            },
        ),
    ]
