# Generated by Django 4.2.30 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_alter_movimientoinventario_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='planificada', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='inventario.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_materiales', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Lista de materiales',
                'verbose_name_plural': 'Listas de materiales',
            },
        ),
        migrations.CreateModel(
            name='ComponenteOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumido_en_ordenes', to='inventario.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Componente de la orden',
                'verbose_name_plural': 'Componentes de la orden',
            },
        ),
        migrations.CreateModel(
            name='ComponenteBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.PositiveIntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='inventario.producto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produccion.listamateriales')),
            ],
            options={
                'verbose_name': 'Componente de la receta',
                'verbose_name_plural': 'Componentes de la receta',
                'unique_together': {('lista', 'insumo')},
            },
        ),
    ]
