# Generated by Django 4.2.30 on 2026-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_componentebom_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='ordenproduccion_numero_unico_por_empresa'),
        ),
    ]
