# Generated by Django 4.2.30 on 2026-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_empresa_lineacompra_empresa_proveedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='compra_numero_unico_por_empresa'),
        ),
    ]
