# Generated by Django 4.2.30 on 2026-09-03 03:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0010_cotizacion_proyecto_cuentacobro_cotizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_grupoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='ventas.cliente')),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['cliente__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del trabajo')),
                ('unidad', models.CharField(blank=True, default='un', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor unitario')),
                ('notas', models.CharField(blank=True, help_text='Ej. estado de la factura, observaciones internas.', max_length=300, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bitacora', to='ventas.cotizacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bitacora', to=settings.AUTH_USER_MODEL)),
                ('cuenta_cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bitacora', to='ventas.cuentacobro')),
                ('empresa', models.ForeignKey(default=1, help_text='Inquilino (empresa) al que pertenece este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bitacora.sede')),
            ],
            options={
                'verbose_name': 'Ítem de bitácora',
                'verbose_name_plural': 'Ítems de bitácora',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='sede_nombre_unica_por_cliente'),
        ),
    ]
